matrix:
  include:
    - language: python
    python:
      - "3.6"
    install:
      - pip install pytest pytest-cov
      - pip install coveralls
    script:
      - bash testAppServer.sh
    after_success:
      - coveralls

notifications:
  email:
    - czarniana@gmail.com
