language: python
python:
  - "3.5"
install:
  - pip install pytest-cov
  - pip install python-coveralls
before script:
  - py.test --cov=UberClon test/
script:
  - bash test.sh
after_success:
  - coveralls
